### PR TITLE
Fix unexpected animation in transition when user click not once

### PR DESCRIPTION
**Pull request by yuanyan**

### CODE REVIEW

**Review by temper357 — DISMISSED** [review]
LGTM

**Review by wssgcg1213 — APPROVED** [review]

**Review by andycall — DISMISSED** [review]

**Review by answershuto — DISMISSED** [review]

**Comment by wssgcg1213** [comment]
Waiting for CI finish @andycall

**Comment by andycall** [comment]
@yuanyan 测试挂了

**Comment by wssgcg1213** [comment]
@andycall Could we see the snapshot files in actions?

**Comment by andycall** [comment]
> @andycall Could we see the snapshot files in actions?

just merge main branch and rerun the test

**Review by wssgcg1213 — APPROVED** [review]

**Review by andycall — APPROVED** [review]

**Pull request merged**
